# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  前端: /tags/前端
  笔记: /tags/笔记
  读书: /tags/读书

# SubNav
subnav:
  github: "https://github.com/etc1208"
  weibo: "http://weibo.com/2707541947/profile?topnav=1&wvr=6&is_all=1"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/yang-he-93"
  #douban: "#"
  mail: "599068284@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: "http://imgsrc.baidu.com/forum/w%3D580/sign=baf99437e51190ef01fb92d7fe199df7/743caa1ea8d3fd1f7ef8e6e0324e251f97ca5faa.jpg"

#你的头像url
avatar: "http://imgsrc.baidu.com/forum/w%3D580/sign=baf99437e51190ef01fb92d7fe199df7/743caa1ea8d3fd1f7ef8e6e0324e251f97ca5faa.jpg"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 
duoshuo: etc1208
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: "我叫杨赫，来自北京邮电大学，现在是计算机学院在读研究生。热爱前端，热爱绘画和健身，喜欢分享"
